# Generated by Django 5.2.6 on 2025-10-17 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='laundry_items/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('items', models.JSONField(blank=True, null=True)),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pickup_address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('scheduled_pickup', models.DateTimeField()),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Diambil'), ('processing', 'Diproses'), ('ready', 'Siap Diantar'), ('delivered', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Belum Dibayar'), ('paid', 'Dibayar'), ('settlement', 'Selesai')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(choices=[('cod', 'Bayar di Tempat (COD/Tunai)'), ('qris', 'QRIS / Transfer Online')], default='cod', max_length=10)),
                ('snap_token', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.laundryitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service')),
            ],
        ),
    ]
