# Generated by Django 5.2.6 on 2025-10-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_discount_order_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notified_customer',
            field=models.BooleanField(default=False),
        ),
    ]
