# Generated by Django 5.2.6 on 2025-10-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('per_kilo', 'Per Kilo'), ('per_item', 'Per Item')], max_length=20)),
                ('duration', models.CharField(choices=[('biasa', 'Biasa (2-3 hari)'), ('sicepat', 'SiCepat (1 hari)'), ('express', 'Express (6 jam)')], default='biasa', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
            ],
        ),
    ]
